# Generated by Django 2.1.11 on 2020-01-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_organization_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_playground',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(blank=True, to='tenants.Tenant'),
        ),
    ]
