# Generated by Django 3.0.2 on 2020-02-02 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_organization_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationinvite',
            name='from_domain',
            field=models.CharField(default='', max_length=256),
        ),
    ]
