# Generated by Django 3.0.3 on 2020-02-10 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_organization_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='tenants.OrganizationProfile'),
        ),
    ]
