# Generated by Django 3.0.9 on 2021-01-31 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_project_slug_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='feature_flags',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='tenants.FeatureFlag'),
        ),
    ]
