# Generated by Django 3.0.9 on 2021-01-30 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0011_project_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
