# Generated by Django 3.0.9 on 2021-01-31 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0012_organization_feature_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='featureflag', to='tenants.Organization'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='tenants.Organization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='feature_flags',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deprecated_org', to='tenants.FeatureFlag'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deprecated_org', to='tenants.OrganizationProfile'),
        ),
    ]
