# Generated by Django 3.0.9 on 2021-01-31 04:36

from django.db import migrations


def forwards(apps, schema_editor):
    Organization = apps.get_model('tenants', 'Organization')

    for org in Organization.objects.all():
        if org.profile is not None:
            org.profile.organization = org
            org.profile.save()

        if org.feature_flags is not None:
            org.feature_flags.organization = org
            org.feature_flags.save()


def backwards(apps, schema_editor):
    ...


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0013_organization_profile_fix'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
