# Generated by Django 3.0.9 on 2021-01-31 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0014_organization_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='feature_flags',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='profile',
        ),
    ]
