# Generated by Django 3.0.9 on 2021-01-31 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0015_organization_fields_remove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureflag',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_flags', to='tenants.Organization'),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='organization',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='tenants.Organization'),
        ),
    ]
