# Generated by Django 2.1.11 on 2019-11-05 02:02

import base.validators
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='/', max_length=2048, validators=[base.validators.validate_path])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mocks.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeaderType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HttpVerb',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'HTTP Verb',
                'verbose_name_plural': 'HTTP Verbs',
            },
        ),
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status_code', models.IntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mocks.Endpoint')),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mocks.HttpVerb')),
            ],
        ),
        migrations.CreateModel(
            name='Params',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('mock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocks.Mock')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='header_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocks.HeaderType'),
        ),
        migrations.AddField(
            model_name='header',
            name='mock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocks.Mock'),
        ),
        migrations.AddField(
            model_name='content',
            name='mock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocks.Mock'),
        ),
    ]
