# Generated by Django 2.1.11 on 2019-10-14 04:01

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HeaderType',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='HttpVerb',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'HTTP Verb',
                'verbose_name_plural': 'HTTP Verbs',
            },
        ),
        migrations.CreateModel(
            name='Mock',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('path', models.CharField(default='/', max_length=955, validators=[core.validators.validate_path])),
                ('params', models.TextField(default='{}', validators=[core.validators.validate_json])),
                ('content', models.TextField(default='{}', validators=[core.validators.validate_json])),
                ('status_code', models.IntegerField(default=200)),
                ('verb', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mocks.HttpVerb')),
            ],
        ),
        migrations.AddField(
            model_name='header',
            name='header_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocks.HeaderType'),
        ),
        migrations.AddField(
            model_name='header',
            name='mock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mocks.Mock'),
        ),
    ]
