# Generated by Django 2.1.11 on 2019-12-25 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('mocks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='content',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='header',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='headertype',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='httpverb',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='tenant',
        ),
        migrations.RemoveField(
            model_name='params',
            name='tenant',
        ),
        migrations.AddField(
            model_name='category',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Organization'),
        ),
        migrations.AddField(
            model_name='content',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Organization'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Organization'),
        ),
        migrations.AddField(
            model_name='header',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Organization'),
        ),
        migrations.AddField(
            model_name='headertype',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Organization'),
        ),
        migrations.AddField(
            model_name='httpverb',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Organization'),
        ),
        migrations.AddField(
            model_name='mock',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Organization'),
        ),
        migrations.AddField(
            model_name='params',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Organization'),
        ),
    ]
