# Generated by Django 2.1.11 on 2019-10-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0001_mocks_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='mock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
