# Generated by Django 3.0.5 on 2020-05-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0009_organization_project'),
        ('mocks', '0002_organization_aware_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='created',
        ),
        migrations.RemoveField(
            model_name='category',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='category',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='content',
            name='created',
        ),
        migrations.RemoveField(
            model_name='content',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='content',
            name='mock',
        ),
        migrations.RemoveField(
            model_name='content',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='category',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='created',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='endpoint',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='header',
            name='created',
        ),
        migrations.RemoveField(
            model_name='header',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='header',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='headertype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='headertype',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='httpverb',
            name='created',
        ),
        migrations.RemoveField(
            model_name='httpverb',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='created',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='params',
            name='created',
        ),
        migrations.RemoveField(
            model_name='params',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='params',
            name='mock',
        ),
        migrations.RemoveField(
            model_name='params',
            name='organization',
        ),
        migrations.AddField(
            model_name='mock',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mocks.Category'),
        ),
        migrations.AddField(
            model_name='mock',
            name='content',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocks.Content'),
        ),
        migrations.AddField(
            model_name='mock',
            name='params',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocks.Params'),
        ),
        migrations.AlterField(
            model_name='mock',
            name='path',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='mocks.Endpoint'),
        ),
        migrations.AlterField(
            model_name='mock',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='mock',
            name='verb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mocks.HttpVerb'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocks.Project'),
        ),
        migrations.AddField(
            model_name='mock',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mocks.Project'),
        ),
    ]
