# Generated by Django 2.1.11 on 2019-11-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0003_auto_20191112_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='params',
            options={'verbose_name_plural': 'Params'},
        ),
        migrations.AlterField(
            model_name='params',
            name='mock',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='mocks.Mock'),
        ),
    ]
