# Generated by Django 3.0.5 on 2020-05-29 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0004_entities_date_aware'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mocks.Project'),
        ),
    ]
