# Generated by Django 3.0.5 on 2020-05-30 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0005_path_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='project',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='content',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='params',
        ),
        migrations.RemoveField(
            model_name='mock',
            name='project',
        ),
        migrations.AddField(
            model_name='content',
            name='mock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocks.Mock'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mocks.Category'),
        ),
        migrations.AddField(
            model_name='params',
            name='mock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mocks.Mock'),
        ),
    ]
