# Generated by Django 3.0.5 on 2020-05-30 04:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0006_mock_content_param_invert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='content',
            name='mock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='mocks.Mock', unique=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='mock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headers', to='mocks.Mock'),
        ),
        migrations.AlterField(
            model_name='mock',
            name='path',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='mocks.Endpoint'),
        ),
        migrations.AlterField(
            model_name='params',
            name='content',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='params',
            name='mock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='params', to='mocks.Mock', unique=True),
        ),
    ]
