# Generated by Django 2.1.11 on 2019-12-19 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0007_nullable_endpoint_category'),
        ('mocks', '0002_organization_aware_models'),
    ]

    operations = [
    ]
