# Generated by Django 3.0.5 on 2020-05-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0007_mock_path_fkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endpoint',
            name='category',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='mocks.Category'),
        ),
    ]
