# Generated by Django 3.0.5 on 2020-08-02 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0011_mock_is_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mock',
            name='title',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
