# Generated by Django 3.0.3 on 2020-02-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_organization_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterField(
            model_name='technology',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
