# Generated by Django 2.1.11 on 2019-11-12 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mocks', '0003_auto_20191112_0222'),
        ('authentication', '0001_multi_tenancy_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='users',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='organization',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Tenant',
        ),
    ]
