# Generated by Django 2.1.11 on 2020-01-19 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, validators=[django.core.validators.MinLengthValidator(limit_value=2)], verbose_name='Apellido'),
        ),
    ]
