# Generated by Django 3.0.3 on 2020-02-08 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_blank_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneOffToken',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one_off_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': ('One Off Token',),
                'verbose_name_plural': 'One Off Tokens',
            },
        ),
    ]
