name: Dockerization

on:
  push:
    branches:
      - master
      - staging
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Log in to Docker Registry
      run: |
        docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: Builds Docker image
      run: |
        docker build -t ldelelis/mockserver:${GITHUB_REF##*/} .
    - name: Pushes built Docker image
      run: |
        docker push ldelelis/mockserver:${GITHUB_REF##*/}
    - name: Logs out from Docker Registry
      run: |
        docker logout
