# Generated by Django 2.1.9 on 2019-06-23 17:17

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mock',
            name='id',
        ),
        migrations.AlterField(
            model_name='mock',
            name='path',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, validators=[core.validators.validate_path]),
        ),
    ]
