# Generated by Django 2.1.11 on 2019-09-01 18:17

import core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mock_headers'),
    ]

    operations = [
        migrations.CreateModel(
            name='HttpVerb',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='mock',
            name='params',
            field=models.TextField(blank=True, null=True, validators=[core.validators.validate_json]),
        ),
        migrations.AddField(
            model_name='mock',
            name='title',
            field=models.CharField(default='', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mock',
            name='path',
            field=models.CharField(max_length=955, validators=[core.validators.validate_path]),
        ),
        migrations.AlterField(
            model_name='mock',
            name='verb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.HttpVerb'),
        ),
    ]
