# Generated by Django 2.1.11 on 2019-10-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190901_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='httpverb',
            options={'verbose_name': 'HTTP Verb', 'verbose_name_plural': 'HTTP Verbs'},
        ),
        migrations.AddField(
            model_name='mock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
